---
driver:
  name: vagrant

provisioner:
  name: salt_solo
  is_file_root: true
  state_top_from_file: true
  dependencies:
    - { path: '../formulas/systemd-formula', name: 'systemd' }
    - { path: '../formulas/openssh-formula', name: 'openssh' }
    - { path: '../formulas/users-formula', name: 'users' }
    - { path: '../formulas/chrony-formula', name: 'chrony' }
    - { path: '../formulas/salt-formula', name: 'salt' }


platforms:
  - name: debian/jessie64
    driver:
      vagrantfiles:
        - .vagrantfile_kitchen_disks.rb
      customize:
        memory: 2048
      network:
        - [ "private_network", {ip: "192.168.33.167"} ]


suites:
  - name: default
    salt_version: 2016.3.3
    run_list:
    attributes:

  - name: default_xbtsyslog
    provisioner:

      grains:
        roles:
          - xbt-syslog
